services:
  clickhouse-test:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: clickhouse-test
    restart: 'no'
    ports:
      - "9000:9009"
    environment:
      TZ: ${TZ}
      ulimit: ${ULIMIT}

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # tabix:
  #   container_name: clickhouse-tabix
  #   image: spoonest/clickhouse-tabix-web-client
  #   ports:
  #     - "8080:80"